### ISSUE TITLE
PixelAdmin builder not working

### ISSUE THREAD

**Issue by rodroll** [smnedelko/PixelAdmin#2]
Hi, I bought the PixelAdmin Theme. 
The Pixel admin builder is not working. Every time a try to execute it, I get the message "Before continue, please install Nodejs". Nodejs is installed and I added the path to the nodejs executable file. 
I have a windows 10 64bit.

**Comment by smnedelko** [comment]
Hi rodroll,

Try to execute the next commands in the command prompt (`Win + R`, then `cmd.exe`) to check nodejs availability:

`node -v`
`npm -v`

you must get something like:

v7.2.1
3.10.10

Let me know about the result.

**Comment by rodroll** [comment]
Hi, thanks for the reply.
Same result:
node - v7.2.1
npm - 3.10.10

**Comment by smnedelko** [comment]
Hi rodroll,

It's strange. I made fresh install of Win 10 x64 + Node.js v7.2.1, but I cannot reproduce the issue - Builder is launched correctly... 

Builder checks nodejs availability by executing two commands `node -v` and `npm -v` using `child_process.execSync`. Try to reproduce this behaviour.

In the command prompt run the next commands:

`node`
`String(require('child_process').execSync('node -v'))`
`String(require('child_process').execSync('npm -v'))`

The last two commands must return the next result:

'v7.2.1\r\n'
'3.10.10\n'

Also check your system paths for duplicates. Node.js executable path must be like `C:\Program Files\nodejs\`

**Comment by rodroll** [comment]
Hi smnedelko,

I got the expected result:
'v7.2.1\r\n'
'3.10.10\n'
Just checked the system paths. Deleted, restarted, added the variables again, restarted the computer and still, no luck.

**Comment by smnedelko** [comment]
Ok, It seems like problem is not in Builder itself. Try the next variants:

1. Run app with administrator privileges

2. Set owner - right click on exe > Properties > Security > Advanced > Find "Owner" label and click Change > Enter your username > OK > OK > OK

3. Copy `pixeladmin` directory to the system disk (for example, C:\Users\Username\pixeladmin-2.0.0)

4. Check that your antivirus is not blocks Builder. Try to turn it off - don't worry, each release is scanned by Kaspersky antivirus

**Comment by rodroll** [comment]
I tried them all and no success.
I also tried to run the builder on another user account on the same computer and it worked. I tried again in my account (admin) and it did not work.

**Comment by rodroll** [comment]
I spent the 5 days trying several things, but none of them worked. For other reason, i bought a new computer and now it is working.
