### ISSUE TITLE
Custom SCSS File is not compiled

### ISSUE THREAD

**Issue by efriandika** [smnedelko/PixelAdmin#4]
I follow the docs to create a custom scss file. But, it does not works perfectly. I need to put ```@import '../custom/custom';``` at the end of pixeladmin.scss.  in documentations, there is no info to put custom.scss at the end of pixeladmin.scss

Is the docs wrong ? or am I wrong..?

Please help me.. :)

**Comment by smnedelko** [comment]
Hi efriandika,

You're right. Customization structure is created by Builder app when building bundle. If you're not using builder then you need to add `../custom/custom` path into the `pixeladmin.scss` file manually.

P.S. I have implemented support for the customization by default (with or without builder). It will be available in the next update (on the first or second week of January). 

Thank You.

**Comment by efriandika** [comment]
Thanks @smnedelko for the information.
I am waiting for that.. 💃
