### ISSUE TITLE
Using pixeladmin 2.2, Builder.app getting fatal error

### ISSUE THREAD

**Issue by jackchusf** [smnedelko/PixelAdmin#7]
Hi, I'm running Mac Sierra. I'm running Builder-darwin-x64/Builder.app. It's getting this error "Application can't find PixelAdmin's project root.". Can you help?

**Comment by smnedelko** [comment]
Hi jackchusf,

Please ensure that builder directory within pixeladmin directory. Builder scans parent directories for pixeladmin-specific files.

**Comment by jackchusf** [comment]
Hi, it is within the pixeladmin directory.

**Comment by vudaltsov** [comment]
same issue. MacBook Pro 2016, macOS 10.12.3
Builder.app is within pixeladmin dir

**Comment by smnedelko** [comment]
Fixed in 2.3.0

**Comment by vudaltsov** [comment]
yes it works, thx!
