### ISSUE TITLE
Using Builder, theme color of darklight-blue was incorrect.

### ISSUE THREAD

**Issue by ryush00** [smnedelko/PixelAdmin#8]
To use darklight-blue theme, I used Builder App to compile assets. Of course I checked `Include dark version` checkbox.

![image](https://cloud.githubusercontent.com/assets/4997174/22626203/de8dba96-ebeb-11e6-84e8-9691d82b7282.png)

But color of dropdown menu was wrong. This should be like this.

![image](https://cloud.githubusercontent.com/assets/4997174/22626218/0eb2bdfc-ebec-11e6-88c3-92661d725890.png)

I think this was bug. Because when I copied `darklight-blue.min.css` file of herokuapp demo to my project css, it worked well.

Thank you.

OS: Mac OS X 10.12.2

**Comment by smnedelko** [comment]
Hi ryush00,

Could you copy&paste here content of `{your-build-directory}/scss/themes/darklight-blue/darklight-blue.scss` file? I think it's a bug of Builder.

Thank You.

**Comment by ryush00** [comment]
https://gist.github.com/ryush00/d1d8de0139b1b3c24eaa5a0f4b16d1e0

**Comment by ryush00** [comment]
And I have another issue similar to #3. px-nav is not working on mobile (small screen).

**Comment by ryush00** [comment]
And Now I think I found way to resolve menu issue. Moving script to above `</body>` tag.

**Comment by smnedelko** [comment]
Hi ryush00,

this is a Builder bug. As a temporary solution, insert the next line:

```
@import '../../variables-dark';
```

before

```
@import '../../variables';
```

in the `{your-build-directory}/scss/themes/darklight-blue/darklight-blue.scss` file.

**Comment by smnedelko** [comment]
Fixed in 2.3.0
